### ISSUE TITLE
Add sector to server if not exist

### ISSUE THREAD

**Issue by Suput** [RTUITLab/MagicCircle#2]
При создании связи между профилем и сектором, нужно проверять, что сектор существует на сервере. Если его нет, то добавить

Пайплайн примерно такой: попробовать добавить связь, если вернулось 404, то создать сектор на сервере и попробовать снова

**Comment by gextnen** [comment]
Хорошо, только нужно обработать вариант, когда необходимо добавить несколько секторов: Допустим ['Sect1', 'Sect2', Sect3] и никакого из них нет в базе. Сейчас /sector принимает строку "coords": "coords". 
При отправке "coords": ['Sect1', 'Sect2', Sect3] бек сломается. Думаю нужно сделать, чтобы /sector на вход принимал массив, а не строку

**Comment by gextnen** [comment]
Сделал, пока для одного сектора работает. Как только бек будет принимать множество секторов, доделаю и закрою issue

**Comment by Suput** [comment]
Да, сегодня должно появится

**Comment by Suput** [comment]
@malovvan можно переделывать под новый бэк
