### ISSUE TITLE
Show empty description

### ISSUE THREAD

**Issue by Suput** [RTUITLab/MagicCircle#3]
Сейчас нажатие на сектор, показывает его описание, однако если нажать на сектор, у которого нет описания, то покажется описание предыдщего открытого сектора
То есть когда пользователь закрывает модальное окно, нужно очищать поля. Иначе они просто запоминаются и показываются на тех секторах, у которых нет описания

**Comment by gextnen** [comment]
Сделал, со следующим коммитом запушу
