### ISSUE TITLE
Align dots in sector description

### ISSUE THREAD

**Issue by Suput** [RTUITLab/MagicCircle#4]
Почему-то первая точка съезжает вправо, хотя в описании всё окей
Описание:
```js
'L6-T1': {
        id: 'L6-T1',
        name: 'Стажёр',
        // Описание должности
        direction: 'Сотрудник, цель которого — получение знаний и первого опыта. ' +
            'В зависимости от местных условий, может быть нанят в отдел и работать с простейшими задачами, ' +
            'либо проходить специализированную стажировку, отделенную от настоящих задач вообще.',
        // Чем занимается
        typeOfActivity: 'Обучается в профессии, вливается в компанию, развивается и приобретает навыки ' +
            'для работы над дальнейшими проектами',
        // Необходимые навыки
        requirements: '•\tГотовность к обучению в отрасли\n' +
            '•\tУмение анализировать свои ошибки\n' + 
            '•\tКоммуникативные навыки\n' + 
            '•\tБазовые знания в ИТ\n' + 
            '•\tБазовые навыки программирования\n' + 
            '•\tПонимание устройства программных продуктов',
        // Как стать
        howBecome: 'Стать стажёром можно не имея большого опыта разработки, однако базовые навыки должны присутствовать. ' +
            'Главное, чтобы человеку была интересна сфера IT и он хотел развиваться в этом направлении',
        // Куда расти
        careerGrowth: 'После стажёра сотрудник может занять должность младшего разработчика'
    },
```
Скрин:
![image](https://user-images.githubusercontent.com/40500378/152977537-2d34b8a9-3d3d-4430-bdad-2ae757e6758c.png)

**Comment by gextnen** [comment]
Тут не так просто, как кажется. Из-за особенностей css white-space(сейчас white-space: pre-wrap, ставит автоматически пробел в начале абзаца ). Есть три путя: 
1. white-space: pre-line. Точки встанут как надо, Но не будет отображаться табуляция('\t') - первый скрин

![1](https://user-images.githubusercontent.com/56535380/153039185-8d32260b-d42b-4f74-9d8b-db4af75ff84f.jpg)

2. white-space: pre-wrap. Оставить, как есть, но добавить в текстовки пробелы перед '•'. - второй скрин

![image](https://user-images.githubusercontent.com/56535380/153039664-59d9ecd5-4f18-4425-8f12-28443def8e3d.png)

3. white-space: pre-wrap. Добавить какой-то текст перед списком, чтобы он съел пробел. - третий скрин

![image](https://user-images.githubusercontent.com/56535380/153040160-623b086c-3860-4a9c-9244-68addc0de655.png)

**Comment by gextnen** [comment]
Нужен совет, как лучше сделать

**Comment by Suput** [comment]
@malovvan
Можно оставить как есть, чтобы всегда видеть проблему перед глазами
Моё предложение 1: парсить это в `<span>`
Моё предложение 2: хранить это описание на бэке и сделать его в виде `markdown`

**Comment by Suput** [comment]
Перейдём на markdown текст
